# Generated by Django 2.1.2 on 2018-10-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CubeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cube_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CubeHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cube_header',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cubedetail',
            name='cube_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.CubeHeader'),
        ),
    ]
